-- MySQL Script generated by MySQL Workbench
-- Fri Aug 20 17:55:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_projeto_ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_projeto_ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_projeto_ecommerce` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_projeto_ecommerce` ;

-- -----------------------------------------------------
-- Table `db_projeto_ecommerce`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto_ecommerce`.`tb_categorias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `casa_e_construcao` VARCHAR(250) NULL DEFAULT NULL,
  `para_levar` VARCHAR(250) NULL DEFAULT NULL,
  `jardinagem` VARCHAR(250) NULL DEFAULT NULL,
  `culinaria` VARCHAR(250) NULL DEFAULT NULL,
  `higiene_e_cosmeticos` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_projeto_ecommerce`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto_ecommerce`.`tb_produto` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NULL DEFAULT NULL,
  `descricao` VARCHAR(250) NULL DEFAULT NULL,
  `marca` VARCHAR(250) NULL DEFAULT NULL,
  `tamanho` BIGINT NULL DEFAULT NULL,
  `fk_categorias` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categorias` (`fk_categorias` ASC) VISIBLE,
  CONSTRAINT `tb_produto_ibfk_1`
    FOREIGN KEY (`fk_categorias`)
    REFERENCES `db_projeto_ecommerce`.`tb_categorias` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_projeto_ecommerce`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto_ecommerce`.`tb_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(250) NULL DEFAULT NULL,
  `email` VARCHAR(250) NULL DEFAULT NULL,
  `senha` BIGINT NULL DEFAULT NULL,
  `fk_produto` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_produto`
    FOREIGN KEY (`id`)
    REFERENCES `db_projeto_ecommerce`.`tb_produto` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
